version: "3.9"

services:
  chroma:
    build: .

    ports:
      - "8000:8000"

    environment:
      INITIALIZE: "true"
      CHROMA_DB_PATH: "/data/db"
      DOCS_PATH: "/data/docs"

    volumes:
      - ./chroma-data:/data/db
      - ./docs:/data/docs
