# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\tgenerated\"\r\n\x0bPingRequest\"\x1e\n\x0cPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"@\n\x07Request\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\"T\n\x08Response\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05reply\x18\x02 \x01(\t\x12\x14\n\x0cqueue_length\x18\x03 \x01(\x05\x12\x0f\n\x07retries\x18\x04 \x01(\x05\x32{\n\rWorkerService\x12\x31\n\x06Handle\x12\x12.generated.Request\x1a\x13.generated.Response\x12\x37\n\x04Ping\x12\x16.generated.PingRequest\x1a\x17.generated.PingResponseB\x14Z\x12/master/generated/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022/master/generated/'
  _globals['_PINGREQUEST']._serialized_start=27
  _globals['_PINGREQUEST']._serialized_end=40
  _globals['_PINGRESPONSE']._serialized_start=42
  _globals['_PINGRESPONSE']._serialized_end=72
  _globals['_REQUEST']._serialized_start=74
  _globals['_REQUEST']._serialized_end=138
  _globals['_RESPONSE']._serialized_start=140
  _globals['_RESPONSE']._serialized_end=224
  _globals['_WORKERSERVICE']._serialized_start=226
  _globals['_WORKERSERVICE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
